name: "Set up Cog"
description: "Set up a specific version of Cog and add it to the PATH"
runs:
  using: "composite"
  steps:
    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/cog
        key: ${{ runner.os }}-cog-${{ hashFiles('action.yml') }}

    - name: Install cog
      shell: bash
      run: |
        if [ -x "/usr/local/bin/cog" ]; then
          echo "cog is already installed and cached"
        else
          sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          sudo chmod +x /usr/local/bin/cog
        fi
